import React from "react";
import Metadata from "next";
import Link from "next/link";
import { Header } from "@/components/Header";
import { Footer } from "@/components/Footer";

export const metadata = {
  title: "Privacy Policy | Vicky Diagnostics",
  description: "Privacy Policy and data protection guidelines for Vicky Diagnostics patients and website visitors.",
};

export default function PrivacyPolicyPage() {
  return (
    <div className="min-h-screen flex flex-col bg-slate-50">
      <Header />

      <main className="flex-1 max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="bg-white rounded-2xl p-8 sm:p-12 shadow-sm border border-slate-200 space-y-8">
          
          {/* Header */}
          <div className="border-b border-slate-100 pb-6">
            <div className="inline-block px-3 py-1 bg-primary/10 text-primary text-xs font-bold rounded-full mb-3">
              Legal & Compliance
            </div>
            <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">Privacy Policy</h1>
            <p className="text-slate-500 text-sm mt-2">Effective Date: January 1, 2026 | Last Updated: July 2026</p>
          </div>

          {/* Policy Sections */}
          <div className="prose prose-slate max-w-none text-sm text-slate-700 leading-relaxed space-y-6">
            <p>
              At <strong>Vicky Diagnostics</strong>, accessible from our online portal and diagnostic booking system, protecting the privacy and security of our patients&#39; personal and medical information is our utmost priority. This Privacy Policy outlines the types of information we collect, how it is used, stored, and safeguarded.
            </p>

            <h2 className="text-lg font-bold text-slate-900 pt-2 border-b border-slate-100 pb-2">
              1. Information We Collect
            </h2>
            <p>We collect information necessary to provide accurate diagnostic testing and healthcare services:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Personal Identifiable Information:</strong> Full name, age, gender, date of birth, phone number, email address, and home collection address.</li>
              <li><strong>Health & Diagnostic Data:</strong> Test requisitions, doctor prescriptions, sample collection timestamps, and test results generated by our certified laboratories.</li>
              <li><strong>Payment Information:</strong> Transaction details processed securely through PCI-DSS compliant payment gateways (Razorpay). We do not store credit card numbers, CVVs, or UPI PINs on our servers.</li>
              <li><strong>Technical Data:</strong> IP address, browser type, device information, and site interaction analytics to improve user experience.</li>
            </ul>

            <h2 className="text-lg font-bold text-slate-900 pt-2 border-b border-slate-100 pb-2">
              2. How We Use Your Information
            </h2>
            <p>The information we collect is strictly used for clinical and service purposes:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Scheduling, dispatching phlebotomists, and conducting home sample collections.</li>
              <li>Processing lab samples and delivering accurate digital diagnostic reports via SMS, WhatsApp, and encrypted web downloads.</li>
              <li>Sending transaction confirmation notifications, invoice billing, and appointment status alerts via OTP verification.</li>
              <li>Complying with applicable legal, statutory, and clinical accreditation regulations.</li>
            </ul>

            <h2 className="text-lg font-bold text-slate-900 pt-2 border-b border-slate-100 pb-2">
              3. Data Sharing & Confidentiality
            </h2>
            <p>
              We maintain strict medical confidentiality. We do not sell, rent, or trade your personal or medical data to third-party advertisers or data brokers. Data is shared strictly under the following limited circumstances:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li><strong>Authorized Lab Personnel & Pathologists:</strong> Certified medical technicians and doctors evaluating diagnostic test parameters.</li>
              <li><strong>Payment Gateway Partners:</strong> Razorpay Software Private Limited for verifying payment transactions and issuing refunds.</li>
              <li><strong>Regulatory & Legal Mandates:</strong> Government health authorities when required by law (e.g., reportable infectious diseases under health department guidelines).</li>
            </ul>

            <h2 className="text-lg font-bold text-slate-900 pt-2 border-b border-slate-100 pb-2">
              4. Data Security & Storage
            </h2>
            <p>
              We employ industry-standard technical and organizational security measures, including end-to-end SSL/TLS encryption for online data transmission, strict database access controls, and secure OTP verification for report access to prevent unauthorized access, alteration, or disclosure.
            </p>

            <h2 className="text-lg font-bold text-slate-900 pt-2 border-b border-slate-100 pb-2">
              5. Patient Rights & Contact Information
            </h2>
            <p>
              You have the right to request access to your test history, update your contact details, or raise any privacy concerns. For queries regarding your data or this policy, please reach out to our privacy officer:
            </p>
            
            <div className="bg-slate-50 rounded-xl p-4 border border-slate-200 text-xs space-y-1 text-slate-800 font-medium">
              <p className="font-bold text-slate-900">Vicky Diagnostics Privacy & Grievance Office</p>
              <p>📍 101 Diagnostic Towers, Madhapur, Hyderabad, Telangana 500081</p>
              <p>📞 Phone: +91 93981 75183</p>
              <p>✉️ Email: <a href="mailto:support@vickydiagnostics.com" className="text-primary hover:underline">support@vickydiagnostics.com</a></p>
            </div>
          </div>

          <div className="pt-6 border-t border-slate-100 flex justify-between items-center text-xs">
            <Link href="/" className="text-primary font-bold hover:underline">
              ← Return to Home
            </Link>
            <Link href="/terms-and-conditions" className="text-slate-500 hover:text-slate-900 hover:underline">
              Terms & Conditions →
            </Link>
          </div>

        </div>
      </main>

      <Footer />
    </div>
  );
}
